export const RENDER_LIST_PEOPLE = "RENDER_LIST_PEOPLE"
export const RENDER_LIST_PEOPLE_SUCCESS = "RENDER_LIST_PEOPLE_SUCCESS"
export const RENDER_LIST_PEOPLE_FAIL = "RENDER_LIST_PEOPLE_FAIL"

export const RENDER_LIST_SHIPS = "RENDER_LIST_SHIPS"
export const RENDER_LIST_SHIPS_SUCCESS = "RENDER_LIST_SHIPS_SUCCESS"
export const RENDER_LIST_SHIPS_FAIL = "RENDER_LIST_SHIPS_FAIL"

export const RENDER_LIST_PLANETS = "RENDER_LIST_PLANETS"
export const RENDER_LIST_PLANETS_SUCCESS = "RENDER_LIST_PLANETS_SUCCESS"
export const RENDER_LIST_PLANETS_FAIL = "RENDER_LIST_PLANETS_FAIL"
